### ISSUE TITLE
Posix_Spawn Fatal Fork and Spawn Error

### ISSUE THREAD

**Issue by IQubic** [InternetUnexplorer/discord-overlay#10]
So, I've been using this overlay for quite a while now. However, I just ran a system update and things are broken. When I try to launch `DiscordCanary` from the command line, I get the following output and then it just hangs. I have to use Ctrl-C to terminate the process.
```
[Nix] Disabling updates already done
[16352:1027/085919.895632:FATAL:fork_and_spawn.cc(196)] posix_spawn: No such file or directory (2)
```

My nixos config can be found here: https://github.com/IQubic/nixos-config
I'm pulling in your overlay by making it an input in `flake.nix` and then telling nix to use that as an overlay a bit further in the same file.

**Comment by InternetUnexplorer** [comment]
Unfortunately, I think this is an issue with the latest version of Discord Canary itself; I'm seeing people reporting the same error [here](https://bugs.archlinux.org/task/76314) and [here](https://www.reddit.com/r/discordapp/comments/yerhzq/discord_canary_on_windows_now_using_electron_17/itzv6xz/) so I don't think it's NixOS-specific. :(

I've reverted the commit for now to match the previous version (0.0.140, also in Nixpkgs), you'll need to put [`SKIP_HOST_UPDATE` in your `settings.json`](https://nixos.wiki/wiki/Discord#Discord_wants_latest_version) to use it.

**Comment by InternetUnexplorer** [comment]
Ok, after looking through `strace` it looks like they forgot to include `chrome_crashpad_handler`. I pushed what is hopefully a quick fix, can you let me know if it works for you?

**Comment by IQubic** [comment]
@InternetUnexplorer Your latest fix has worked for me. I just did a `nix flake update` followed by a `nixos-rebuild switch` and now I have the latest DiscordCanary. Thanks for everything.

**Comment by InternetUnexplorer** [comment]
Glad it worked, thanks for bringing it to my attention. I'll try to keep an eye on it going forward and remove that fix once it's no longer needed.
